### ISSUE TITLE
Why no GPT-4-Turbo? 

### ISSUE THREAD

**Issue by WhoIsDoctorWho** [pamelafox/openai-messages-token-helper#18]
Once I'm trying to calculate tokens using GPT-4-Turbo, I'm getting the error _"Model gpt-4-turbo not found, defaulting to minimum token limit 4000"_.

Looks like it's missing in **model_helper.py** (MODELS_2_TOKEN_LIMITS, AOAI_2_OAI) 

Is there a reason for that?

**Comment by pamelafox** [comment]
That's because this was designed originally for Azure OpenAI users, who don't have that as a model name. However, I can add support for OpenAI.com specific model names as well:
https://github.com/pamelafox/openai-messages-token-helper/pull/19

**Comment by pamelafox** [comment]
Released 0.1.10 with that model name. Let me know if you run into additional issues. Thanks for filing!
